//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ContosoBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        [StringLength(50), Required]
        public string Title { get; set; }
        [StringLength(50), Required]
        public string Author { get; set; }
        [Range(1000, 2017), Required]
        public Nullable<int> Year { get; set; }
        [Required]
        public Nullable<int> Pages { get; set; }
    }
}
